feat: Add support for AWS Secrets Manager
wandb/terraform-aws-wandb pull request #151
Opened 2023-11-03 05:34 UTC by andrewtruong

2023-11-03 17:50 UTC, elainaRenee commented on examples/public-dns-external/main.tf
> +  }, var.other_wandb_env)
IMO we should make this a dedicated field in the module: https://github.com/wandb/terraform-kubernetes-wandb. Then it's easy to discover and we can add docs for it in that module

2023-11-03 17:53 UTC, elainaRenee commented on examples/public-dns-external/variables.tf
> +}
Looks unused

2023-11-03 18:02 UTC, elainaRenee commented on modules/app_eks/iam-policies.tf
> +  }
I'm not sure we need the lifecycle rule here, I thought this was defaulted to false anyway

2023-11-03 18:08 UTC, elainaRenee commented on modules/app_eks/iam-policy-docs.tf
> +  }
Hmm is there a better default here than allowing access to all secret managers? It looks like the default we are setting for the other policies is `["arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${aws_iam_role.node.name}"] `

2023-11-03 18:11 UTC, elainaRenee commented on variables.tf
> +}
Where does the secret manager get provisioned? Not seeing a module for it

2023-11-06 13:27 UTC, andrewtruong commented on examples/public-dns-external/variables.tf
> +}
This default dict is empty, but I added it anyways to follow the pattern we use in the other terraform repos

2023-11-06 13:30 UTC, andrewtruong commented on modules/app_eks/iam-policies.tf
> +  }
It didn't seem necessary to me either, but I did it to pattern match the lifecycle pattern for this file

2023-11-06 13:46 UTC, andrewtruong commented on modules/app_eks/iam-policy-docs.tf
> +  }
I think limitations are based on the secret, not the secret manager (you can think of the secret manager as some service you can't control)

Our secrets are prefixed, so maybe we can change to:
```
"arn:aws:secretsmanager:*:${data.aws_caller_identity.current.account_id}:secret:${prefix}-*"
```

from:
```
"arn:aws:secretsmanager:*:${data.aws_caller_identity.current.account_id}:secret:*"
```

2023-11-07 20:29 UTC, elainaRenee commented on modules/app_eks/iam-policy-docs.tf
> +  }
Got it. Yeah we need some way to make this a no-op so that we don't give installs access to all secrets. Maybe just put in some junk for the prefix? cc: @gls4 if you have any better ideas here. It be nice to refactor this at some point to not provision the policy at all in the case that no secret manager arn is present.

2023-11-07 20:29 UTC, elainaRenee commented on modules/app_eks/iam-policies.tf
> +  }
I'd just remove it, I think we should get rid of this pattern and actually remove it from all the policies.

2023-11-07 20:29 UTC, elainaRenee commented on examples/public-dns-external/main.tf
> +  }, var.other_wandb_env)
^ to clarify, this is a separate suggestion not blocking this PR

2023-11-07 20:42 UTC, andrewtruong commented on examples/public-dns-external/main.tf
> +  }, var.other_wandb_env)
Thanks, will follow with:
1. Fix in the k8s repo
2. Fix in each of the child repos

2023-11-07 20:44 UTC, andrewtruong commented on modules/app_eks/iam-policy-docs.tf
> +  }
For simplicity, maybe we can just enforce that the prefix is non-null.

I don't think we use the Secret Manager for anything else atm, but maybe in future?

2023-11-07 20:53 UTC, elainaRenee commented on variables.tf
> +}
Is this meant to be the arn of the actual secrets? If so, should it be a list of `secret_arn` ?

2023-11-07 21:03 UTC, gls4 requested changes
Need a few changes. We're best off not creating a node role+policy if secrets aren't being used. And the scope of the permissions has to be limited to the node role and only secrets create/managed by that node. More notes in the comments.

2023-11-08 05:11 UTC, andrewtruong commented on variables.tf
> +}
This shouldn't be here since there isn't explicitly a secret manager ARN, only individual secret ARNs -- removed

2023-11-08 05:11 UTC, andrewtruong commented on modules/app_eks/iam-policy-docs.tf
> +    resources = var.secret_manager_arn == "" || var.secret_manager_arn == null ? ["arn:aws:secretsmanager:*:${data.aws_caller_identity.current.account_id}:secret:*"] : [var.secret_manager_arn]
modified to just do the regex check with prefix

2023-11-08 05:13 UTC, andrewtruong commented on modules/app_eks/iam-policy-docs.tf
> +  }
modified permission to be more tightly scoped

2023-11-08 16:58 UTC, elainaRenee approved these changes
thank you! @gls4 can you take another look?

2023-11-08 17:41 UTC, gls4 commented
Nice work @andrewtruong! Last question: you've applied these changes to a local instance, and they work?

2023-11-08 17:45 UTC, gls4 approved these changes

2023-11-13 17:13 UTC, merged

2023-11-13 17:14 UTC, jsbroks commented
This PR is included in version 3.4.0 :tada: