Init operator
wandb/terraform-aws-wandb pull request #154
Opened 2023-11-15 18:50 UTC by jsbroks

2023-11-15 18:50 UTC, jsbroks commented on main.tf
> +          "alb.ingress.kubernetes.io/inbound-cidrs"      = "0.0.0.0/0"
Idk how to make this work?? Will look into it when I get a chance

2023-11-15 19:51 UTC, jsbroks commented on main.tf
> +Comming soon!
```suggestion
```

2023-11-15 19:52 UTC, jsbroks commented on main.tf
> +          "alb.ingress.kubernetes.io/inbound-cidrs"      = "0.0.0.0/0"
once you add a comma it stops worklng?

2023-12-01 19:23 UTC, wandb-zacharyblasczyk commented on main.tf
> +          "alb.ingress.kubernetes.io/inbound-cidrs"      = "0.0.0.0/0"
I got this working for you @jsbroks

2023-12-01 23:00 UTC, gls4 approved these changes
lgtm

2023-12-18 17:28 UTC, gls4 requested changes
Howdy. So we don't want this written as a module like this -- this needs to be in the root directory in a single file.

2023-12-18 18:43 UTC, jsbroks commented
@gls4 Why not? We do this for filestorage

2023-12-18 18:43 UTC, jsbroks commented
We have also already started rolling this how so it would require terraform surgery

2023-12-18 18:46 UTC, jsbroks commented
If anything it should be a submodule under app_eks

2023-12-18 19:58 UTC, gls4 approved these changes
Let's proceed for now. I may iterate on this later, but let's get things rolled out.

2023-12-18 19:58 UTC, gls4 commented on modules/efs/main.tf
> +resource "aws_security_group" "storage_class_nfs" {
This needs to be re-done as a security group with not inline rules attached. The rules need to be created and associated using the `aws_vpc_security_group_ingress_rule` resource type. If we don't use these resource types, we can run into issues with terraform when it tries to delete/modify security groups.

2023-12-18 19:59 UTC, gls4 requested changes

2023-12-18 19:59 UTC, gls4 commented on modules/app_eks/efs.tf
> +resource "aws_security_group" "storage_class_nfs" {
Let's use the `aws_vpc_security_group_ingress_rule` resource type here instead of inlining the rules. Leaving them inline can cause problems with tags, and can make groups difficult to modify/delete.

2024-01-08 15:28 UTC, merged