feat: adding flags to switch between LB
wandb/terraform-aws-wandb pull request #159
Opened 2024-01-08 15:19 UTC by wandb-zacharyblasczyk

2024-01-08 17:54 UTC, gls4 requested changes

2024-01-08 17:54 UTC, gls4 commented on main.tf
> +  domain_filter = var.domain_name
What does `domain_filter` do, exactly? Previously, this would've held the FQDN for the managed install. What is changing about the way we're using it?

2024-01-08 17:54 UTC, gls4 commented on main.tf
> +  fqdn                      = var.enable_dummy_dns ? "old.${local.fqdn}" : local.fqdn
I understand what we're doing right here, can you expound?

2024-01-08 17:56 UTC, wandb-zacharyblasczyk commented on main.tf
> +  fqdn                      = var.enable_dummy_dns ? "old.${local.fqdn}" : local.fqdn
We are pointing the record at a different DSN name so we don't need to remove/delete this resource in Phase2 if we want to revert.

2024-01-08 18:02 UTC, wandb-zacharyblasczyk commented on main.tf
> +  domain_filter = var.domain_name
We were never actually using external DNS to manage DNS records. I need to still test this in QA-AWS to ensure that external dns is filtering down to the hosted zone it will apply to. 

In my local testing, having this be the full FQDN was not sufficient for external dns to manage the R53 records. 
I had `domain_name` and `subdomain` set. 

similar to what we are doing here: https://github.com/wandb/core/blob/master/services/deployer/terraform/deploy/aws/single-tenant/variables.tf#L29-L36

2024-01-09 22:56 UTC, jsbroks approved these changes

2024-01-10 00:10 UTC, jsbroks approved these changes

2024-01-10 02:48 UTC, jsbroks approved these changes

2024-01-10 03:00 UTC, merged

2024-01-10 03:00 UTC, jsbroks commented
This PR is included in version 4.1.0 :tada: