Added support for encrypting the database and bucket with CMK
wandb/terraform-aws-wandb pull request #182
Opened 2024-02-22 13:43 UTC by velotioaastha

2024-02-22 23:00 UTC, gls4 requested changes
So we're creating a KMS key by default for use with S3 and RDS. I'd like to get rid of the boolean `create_kms_key` and use the default key _unless_ the customer provides us the ARN of a key to use for S3.  The same for the database. This will allow for simpler (cleaner) code in several places, namely where we've terniary operators. 

Let's amend the name of the default KMS key to `kms_default_key` instead of using the word `generic` in the name of variables and modules. Let me know if you have questions and/or would like to discuss.

2024-02-22 23:14 UTC, gls4 requested changes
A few changes requested: variable names, consideration of performance insights key, remove boolean which toggles creation of KMS key.

2024-02-22 23:14 UTC, gls4 commented on main.tf
> +  kms_key_arn_generic = module.kms.key.arn
Let's change this to `default_kms_key`.

2024-02-22 23:14 UTC, gls4 commented on main.tf
> +  s3_kms_key_arn= var.create_kms ? local.kms_key_arn_generic : length(var.bucket_kms_key_arn)> 0 ? var.bucket_kms_key_arn : local.kms_key_arn_generic
I'd like this statement to be a bit less complex. Let's check for and use the customer-provided KMS arn -OR- use the ARN of the default key.

2024-02-22 23:14 UTC, gls4 commented on main.tf
> +  db_kms_key_arn = var.create_kms ?  local.kms_key_arn_generic: length(var.db_kms_key_arn)> 0  ? var.db_kms_key_arn : local.kms_key_arn_generic
Same thing here:  check for and use the customer-provided KMS arn -OR- use the ARN of the default key.

2024-02-22 23:14 UTC, gls4 commented on main.tf
> +  kms_key_arn                      = local.db_kms_key_arn
Can we use the default KMS key/customer-provided KMS key here as well?

2024-02-22 23:14 UTC, gls4 commented on main.tf
> +  kms_key_arn = local.kms_key_arn_generic
Let's change this to`default_kms_key_arn`

2024-02-22 23:14 UTC, gls4 commented on outputs.tf
> +  value       = local.kms_key_arn_generic
Change the name to `default_kms_key_arn`

2024-02-22 23:14 UTC, gls4 commented on variables.tf
> +variable "db_kms_key_arn" {
Change the name in keeping with previous comments.

2024-02-26 08:07 UTC, velotioaastha commented on main.tf
> +  kms_key_arn                      = local.db_kms_key_arn
hey George, 

Actually, this the local variable, is dependent on conditions and separate variables. That's why we named it differently.

This is the place where this variable value is [determined](https://github.com/wandb/terraform-aws-wandb/blob/aastha/encryption/main.tf#L16).

2024-02-26 08:12 UTC, velotioaastha commented
Hey @gls4, We have added changes for performance insights kms key and updated the naming convention for default kms key. 

Can you also suggest on kms ARN conditions. I've added as a comment there. Will update accordingly.
Please review the PR.

2024-02-26 17:23 UTC, gls4 commented on main.tf
> +  s3_kms_key_arn= var.create_kms ? local.kms_key_arn_generic : length(var.bucket_kms_key_arn)> 0 ? var.bucket_kms_key_arn : local.kms_key_arn_generic
So let's do this:

1. Always create the default keyys
2. Use the default keys unless the customer provides them
3. Let's validate the KMS ARN on the customer provided value, so we accept either `null` or a valid ARN.

2024-02-26 17:24 UTC, gls4 commented on main.tf
> +  kms_key_arn                      = local.db_kms_key_arn
Ah, yes. Thank you for clarifying.

2024-02-26 21:28 UTC, gls4 commented on main.tf
> +  db_kms_key_arn = var.create_kms ?  local.kms_key_arn_generic: length(var.db_kms_key_arn)> 0  ? var.db_kms_key_arn : local.kms_key_arn_generic
I like what you've suggested. Having `create_kms` seems redundant, since we're always going to create at least one.

2024-02-26 21:36 UTC, gls4 commented on main.tf
> +  s3_kms_key_arn= var.create_kms ? local.kms_key_arn_generic : length(var.bucket_kms_key_arn)> 0 ? var.bucket_kms_key_arn : local.kms_key_arn_generic
We need to test how validation behaves -- I'm sure there's a way to test for a valid KMS ARN -OR- null, but we need to be sure. That said, I would use a `validation` block something like this:
```
validation {
    # regex(...) fails if it cannot find a match
    condition     = can(regex("^arn:aws:kms:*:${Account}:*/${Id}"))
    error_message = "..."
  }
  ```

2024-02-26 21:37 UTC, gls4 commented
I need to test this. More to come.

2024-02-27 13:33 UTC, velotioaastha commented on main.tf
> +  s3_kms_key_arn= var.create_kms ? local.kms_key_arn_generic : length(var.bucket_kms_key_arn)> 0 ? var.bucket_kms_key_arn : local.kms_key_arn_generic
Hi @gls4,
okay, we can handle this condition with kms arn or null within the condition itself.
One more thing, Should we not assign default key in case create_kms is false and kms_key_arn is null.

2024-02-27 13:44 UTC, velotioaastha commented on main.tf
> +  db_kms_key_arn = var.create_kms ?  local.kms_key_arn_generic: length(var.db_kms_key_arn)> 0  ? var.db_kms_key_arn : local.kms_key_arn_generic
hi @gls4,

okay, so you mean we should simply put this condition only.. 

s3_kms_key_arn= length(var.bucket_kms_key_arn)> 0 ? var.bucket_kms_key_arn : local.default_kms_key

db_kms_key_arn = length(var.db_kms_key_arn)> 0  ? var.db_kms_key_arn : local.default_kms_key

With this, we don't need to create another boolean which was telling us whether to encrypt s3 or not.
Knowing that null will always result in attaching our generic keys. and the bucket will always be encrypted.

2024-02-27 15:57 UTC, gls4 commented on main.tf
> +  db_kms_key_arn = var.create_kms ?  local.kms_key_arn_generic: length(var.db_kms_key_arn)> 0  ? var.db_kms_key_arn : local.kms_key_arn_generic
Yes, that's it! :-)

2024-02-27 18:21 UTC, gls4 commented
Hello! Looks like we might've missed changing a variable name here:
```
 Error: Reference to undeclared local value
│ 
│   on ../../outputs.tf line 51, in output "kms_key_arn":
│   51:   value       = local.kms_key_arn_generic
│ 
│ A local value with the name "kms_key_arn_generic" has not been declared.
```

2024-03-01 05:44 UTC, velotioaastha commented
hey @gls4, all the comments are resolved. And the PR can be reviewed again.

2024-03-07 17:43 UTC, gls4 approved these changes

2024-07-01 21:13 UTC, adityachoudhari26 approved these changes

2024-07-10 12:06 UTC, merged

2024-07-10 12:06 UTC, jsbroks commented
This PR is included in version 4.20.0 :tada: