#179 Connect to AWS S3 and KMS using IAM role for EKS service account
wandb/terraform-aws-wandb pull request #186
Opened 2024-03-05 08:49 UTC by velotioaastha

https://github.com/wandb/terraform-aws-wandb/issues/179

Connect to AWS S3 and KMS using IAM role for EKS service account

2024-03-05 17:17 UTC, gls4 requested changes
All of the IAM policies related to EKS are located in the `iam*.tf` files in the root of the `app_eks` module. I do not want a submodule created for these, as it adds additional complexity without clear benefit. Please integrate the changes following the pattern used for the existing IAM policies applied to the EKS cluster, without the use of additional third-party modules.

2024-03-07 17:38 UTC, gls4 approved these changes
Looks good. Tested locall and against QA.

2024-05-10 16:01 UTC, jsbroks commented on modules/app_eks/iam-policies.tf
> +resource "aws_iam_policy" "irsa_policy" {
```suggestion
resource "aws_iam_policy" "irsa" {
```

2024-05-10 16:01 UTC, jsbroks commented on modules/app_eks/iam-role-attachments.tf
> +resource "aws_iam_policy_attachment" "irsa_policy_attachment" {
```suggestion
resource "aws_iam_policy_attachment" "irsa" {
```

2024-05-10 16:02 UTC, jsbroks commented on modules/app_eks/iam-role-attachments.tf
> +  name       = "irsa-policy-attachment"
This should be based of the namespace or I think it will cause conflicts

2024-05-10 16:02 UTC, jsbroks commented on modules/app_eks/iam-roles.tf
> +resource "aws_iam_role" "irsa_role" {
```suggestion
resource "aws_iam_role" "irsa" {
```

2024-05-10 16:03 UTC, jsbroks requested changes
https://www.terraform-best-practices.com/naming#resource-and-data-source-arguments
> Do not repeat resource type in resource name (not partially, nor completely)

2024-05-15 12:56 UTC, velotioaastha commented on modules/app_eks/iam-role-attachments.tf
> +  name       = "irsa-policy-attachment"
Hey, @jsbroks, you mean we should add namespace prefix in the name attribute ?
`name = "${var.namespace}-irsa-policy-attachment"`

2024-05-15 17:23 UTC, jsbroks commented on modules/app_eks/iam-role-attachments.tf
> +  name       = "irsa-policy-attachment"
yes

2024-05-18 04:31 UTC, merged

2024-05-18 04:32 UTC, jsbroks commented
This PR is included in version 4.11.0 :tada: