feat: Added support s3 endpoints
wandb/terraform-aws-wandb pull request #202
Opened 2024-04-09 09:21 UTC by amanpruthi

2024-04-30 18:46 UTC, jsbroks commented on modules/endpoint/main.tf
> +resource "aws_vpc_endpoint" "endpoint" {
```suggestion
resource "aws_vpc_endpoint" "default" {
```

2024-04-30 18:46 UTC, jsbroks approved these changes

2024-04-30 18:47 UTC, jsbroks requested changes

2024-04-30 18:47 UTC, jsbroks commented on main.tf
> +  private_route_table_id = [module.networking.private_route_table_ids[0],module.networking.private_route_table_ids[1]]
```suggestion
  private_route_table_id =module.networking.private_route_table_ids
```

Does this not work?

2024-05-03 13:37 UTC, amanpruthi commented on main.tf
> +  private_route_table_id = [module.networking.private_route_table_ids[0],module.networking.private_route_table_ids[1]]
Yes worked

2024-05-10 16:01 UTC, jsbroks approved these changes

2024-06-21 12:18 UTC, merged

2024-06-21 12:19 UTC, jsbroks commented
This PR is included in version 4.14.0 :tada: