fix: Update external_dns interval
wandb/terraform-aws-wandb pull request #203
Opened 2024-04-18 16:08 UTC by wandb-zacharyblasczyk

Default is "1m", but we are hitting API rate limiting.

2024-04-18 18:33 UTC, gls4 requested changes
While we do hit rate limits, I'm not sure it's a problem. Please hold until we can touch base.

2024-04-23 17:31 UTC, jsbroks approved these changes
Small changed, not sure we need to block

2024-04-23 19:22 UTC, merged

2024-04-23 19:22 UTC, jsbroks commented
This PR is included in version 4.8.1 :tada:

2024-04-23 19:25 UTC, wandb-zacharyblasczyk commented
Because it was approved**