chore: init database auora module
wandb/terraform-aws-wandb pull request #3
Opened 2021-11-22 22:09 UTC by jsbroks

2021-11-23 14:16 UTC, zythosec requested changes

2021-11-23 14:16 UTC, zythosec commented on modules/database/variables.tf
> +variable "storage_encrypted" {
Database encryption at rest should not be optional. It is a minimum requirement of all security teams/standards/compliance frameworks. We should allow people to bring their own KMS keys, but storage_encrypted should always be true.

2021-11-23 14:16 UTC, zythosec commented on variables.tf
> +  default     = false
Nice!

2021-11-23 14:16 UTC, zythosec commented on modules/database/main.tf
>    length  = 20
Can we bump this to 32?

2021-11-23 14:35 UTC, zythosec commented on variables.tf
> +  default     = false
Need to update README with default value

2021-11-23 15:44 UTC, jsbroks commented on examples/public-dns-external/main.tf
> +  deletion_protection = false
> Public access disabled

This example, is an example of public access

2021-11-23 15:46 UTC, jsbroks commented on modules/app_eks/main.tf
> +  cluster_version = "1.21"
I ment to bump it and tested

2021-11-23 17:03 UTC, zythosec approved these changes

2021-11-23 18:09 UTC, annirudh reviewed
LGTM!

2021-11-23 18:09 UTC, annirudh commented on modules/database/main.tf
> +  description = "${var.namespace}-aurora-db-57-parameter-group"
Let's add the following DB parameters:

```
parameter {
  name = "binlog_format"
  value = "ROW"
}

parameter {
  name = "performance_schema"
  value = "on"
}

parameter {
  name = "slow_query_log"
  value = "on"
}

parameter {
  name = "long_query_time"
  value = 4
}

parameter {
  name = "max_prepared_stmt_count"
  value = "1048576"
}

parameter {
  name = "innodb_online_alter_log_max_size"
  value = "268435456"
}

parameter {
  name = "max_execution_time"
  value = "60000"
}
```

2021-11-23 18:09 UTC, annirudh commented on modules/database/main.tf
> +  engine_version = "5.7.12"
This is a fairly old version. Could we upgrade to at least `5.7.34`?

2021-11-23 18:09 UTC, annirudh commented on modules/database/output.tf
> +  value = "${local.master_username}:${local.master_password}@${module.aurora.cluster_reader_endpoint}/${local.database_name}"
This is cool. Not critical to do now, but eventually we might want to route this into gorilla using the `GORILLA_METADATA_STORE_REPLICA` env var.

2021-11-23 19:30 UTC, annirudh commented on modules/database/main.tf
> +  engine_version = "5.7.12"
Nevermind, looks like we use `5.7.12` for Lyft. Not sure if there's a newer engine version Aurora supports.

2021-11-24 00:31 UTC, merged

2022-02-10 05:19 UTC, jsbroks commented
This PR is included in version 1.0.0 :tada: