fix: Allow EKS addons version config
wandb/terraform-aws-wandb pull request #303
Opened 2024-10-14 10:34 UTC by flamarion

Given the possibility of running different Kubernetes versions, the add-ons config must also be possible to configure to be compatible.

https://docs.aws.amazon.com/eks/latest/userguide/addon-compat.html

2024-10-14 16:14 UTC, danielpanzella requested changes
Should we add some documentation, or pointers to relevant EKS docs for determining the correct addon versions

2024-10-14 16:14 UTC, danielpanzella commented on modules/app_eks/variables.tf
> +  default     = "v2.0.4-eksbuild.1"
I think we should not set defaults in the submodule, since we set them at the parent and always specify, this just creates two places to change it when we want to change the default

2024-10-14 17:16 UTC, zacharyblasczyk commented
@danielpanzella, if we are going to expose variables for this, what do you think about (psudocode)
```hcl
variable "eks_addon_versions" {
  description = "Map of EKS add-ons and their versions."
  type = map(string)
  default = {
    "aws-efs-csi-driver" = "v2.0.4-eksbuild.1",
    "aws-ebs-csi-driver" = "v1.31.0-eksbuild.1",
    "coredns"            = "v1.10.1-eksbuild.11",
    "kube-proxy"         = "v1.28.8-eksbuild.5",
    "vpc-cni"            = "v1.18.2-eksbuild.1"
  }
}

resource "aws_eks_addon" "default" {
  for_each               = var.eks_addon_versions
  cluster_name           = var.namespace
  addon_name             = each.key
  addon_version          = each.value
  resolve_conflicts      = "OVERWRITE"

  depends_on = [
    aws_eks_addon.vpc_cni
  ]
}
```

We could also make a local that has the map for each eks version say 1.26-1.29, and references the local default for the eks version unless you pass in your own map. 

Not sure if the 
```
 depends_on = [
    aws_eks_addon.vpc_cni
  ]  
```
Will be graceful, but I am sure we could just separate that one out if it is an issue.

Then we are only adding one variable that is extensible, and not adding n variables that we have to maintain and might create confusion.

2024-10-14 17:20 UTC, danielpanzella commented
@zacharyblasczyk since the user would or could be overriding the map as a whole, that allows them to accidentally leave out a required addon, no?

2024-10-14 17:23 UTC, zacharyblasczyk commented
We would have a merge like this:
```hcl
locals {
  eks_addon_versions = merge(local.required_addons, var.eks_addon_versions_override)
}
```

2024-10-14 17:23 UTC, zacharyblasczyk commented
So nothing should be left out.

2024-10-15 07:40 UTC, flamarion commented on modules/app_eks/variables.tf
> +  default     = "v2.0.4-eksbuild.1"
Make sense.

2024-10-15 08:05 UTC, flamarion commented
@zacharyblasczyk and @danielpanzella, is it ok to make it simple for now and allow the override? 
I fixed what was suggested about the default duplication and docs.

2024-10-15 18:43 UTC, zacharyblasczyk approved these changes

2024-10-15 19:12 UTC, zacharyblasczyk approved these changes

2024-10-15 20:33 UTC, zacharyblasczyk approved these changes

2024-10-15 20:42 UTC, danielpanzella approved these changes

2024-10-15 20:42 UTC, merged

2024-10-15 20:42 UTC, jsbroks commented
This PR is included in version 5.0.1 :tada: