feat: Allow ebs encrypt, enable IMDSv2 for node groups, fix instance_types
wandb/terraform-aws-wandb pull request #49
Opened 2023-01-26 22:16 UTC by wandb-zacharyblasczyk

This merge request:
- Make all node groups use `http_tokens`. (forces use of launch template)
- Updates the kms policy to allow launch templates to use encrypted ebs volumes.
- Adds `kubernetes_encrypt_ebs_volume` as an input variable. (forces use of launch template)
- Adds `kubernetes_instance_types` as an input variable.
- fixes `instance_types` as it was `instance_type` not being respected.
- Updates documentation and examples.

2023-01-26 22:25 UTC, vanpelt reviewed
Looks great, let's definitely test if this causes any changes that could impact our running services first but all and all looks great.

2023-01-26 22:34 UTC, venky-wandb commented
@wandb-zacharyblasczyk would you mind also taking a screenshot of the `terraform plan` changes for this so that we can measure if it has any impact on existing installs when updated?

2023-01-26 22:36 UTC, wandb-zacharyblasczyk commented
Absolutely @venky-wandb, as soon as I get home I will take care of sharing that.

2023-01-30 17:11 UTC, wandb-zacharyblasczyk commented
@ venky, I created a tf plan with: 
```
terraform plan -out tf-v1.6.0-upgrade.plan -var-file=./variables/sandbox-test.tfvars
terraform show tf-v1.6.0-upgrade.plan > tfplan-v1.6.0-upgrade.ansi 
```
You can run `less -R tfplan-v1.6.0-upgrade.ansi` to view with colors. 
[tfplan-v1.6.0-upgrade.zip](https://github.com/wandb/terraform-aws-wandb/files/10538114/tfplan-v1.6.0-upgrade.zip)

SS below 👇 
![Screen Shot 2023-01-30 at 10 58 06 AM](https://user-images.githubusercontent.com/77289967/215546147-1ae82446-5aa2-44a8-a556-95031aeeff94.png)
![Screen Shot 2023-01-30 at 10 58 42 AM](https://user-images.githubusercontent.com/77289967/215546153-5b4831ee-7ba8-4012-8709-6c3574cfed16.png)
![Screen Shot 2023-01-30 at 11 08 23 AM](https://user-images.githubusercontent.com/77289967/215546157-2d8a570b-66e7-4e5b-8cf1-f828277731c3.png)

2023-01-31 01:56 UTC, vanpelt approved these changes

2023-01-31 01:56 UTC, vanpelt commented on modules/app_eks/main.tf
> +      disk_kms_key_id        = var.kms_key_arn,
Wanted to double check terraform is happy if this is an empty string.

2023-02-03 19:33 UTC, wandb-zacharyblasczyk commented
@jsbroks, per your recommendation I have moved the launch template feature behind a feature flag. 

Please note that I had to duplicate values in the _"legacy"_ `primary` node group. We can clean this up after this is applied to all our managed instances. 

I tested the upgrade path for v1.5.3 (in use by deployer) and 1.6.0. 

1.5.3 upgrade with `kubernetes_use_launch_template` set to `false`: 
![Screen Shot 2023-02-03 at 1 17 30 PM](https://user-images.githubusercontent.com/77289967/216689327-3c58125d-5b2f-42c4-a419-d07c8869b3a9.png)
![Screen Shot 2023-02-03 at 1 17 46 PM](https://user-images.githubusercontent.com/77289967/216689323-2187c7bb-283c-4de8-9010-3fb484e5d260.png)
No node group replaced.

1.6.0 upgrade with `kubernetes_use_launch_template` set to `false`: 
![Screen Shot 2023-02-03 at 1 13 41 PM](https://user-images.githubusercontent.com/77289967/216689569-abd18eeb-aaba-47cc-963a-9f78a9335159.png)
![Screen Shot 2023-02-03 at 1 14 06 PM](https://user-images.githubusercontent.com/77289967/216689600-624e084e-375a-4b44-aa73-8ee64b0b65ea.png)
No node group replaced.

I also tested 1.5.3 with `kubernetes_use_launch_template` unset (defaults to `true`):
![Screen Shot 2023-02-03 at 1 27 28 PM](https://user-images.githubusercontent.com/77289967/216690463-30840c9c-3151-4b88-9bfa-cfb758034b32.png)
![Screen Shot 2023-02-03 at 1 27 50 PM](https://user-images.githubusercontent.com/77289967/216690534-120aebce-3742-4659-82b8-9e5f521b4b10.png)
![Screen Shot 2023-02-03 at 1 28 22 PM](https://user-images.githubusercontent.com/77289967/216690625-f4e5dcc5-b92d-439e-a4ff-9ad0ada70855.png)
![Screen Shot 2023-02-03 at 1 28 37 PM](https://user-images.githubusercontent.com/77289967/216690692-0ca6c721-e0bd-4e15-ba94-40b04dfda29d.png)
Node group replaced. **_About a 2-3 min outage as the pod reschedules._** 

Please advise on what instance type we want to use. I used `m5.xlarge` as it is what was set in the template originally. 
<img width="1442" alt="Screen Shot 2023-02-03 at 1 29 59 PM" src="https://user-images.githubusercontent.com/77289967/216691574-b7ac81b7-c467-424b-906d-abd9081b7d72.png">

2023-02-03 20:00 UTC, vanpelt approved these changes
Looks good.  We'll still need to be careful with existing dedicated installs and ensure override the default true / manage the downtime when upgrading.

2023-02-03 20:01 UTC, vanpelt commented on variables.tf
> +  description = "Enable launch template"
Let's make this description more clear.  The primary purpose of this was to ensure EBS volumes are encrypted so we should likely say something about that.

2023-02-03 22:33 UTC, jsbroks requested changes
-- blocking, to make sure I get a chance to review

2023-02-03 22:59 UTC, jsbroks commented on modules/app_eks/main.tf
>    }
```suggestion
  node_groups = {
    primary = {
      version                = var.cluster_version,
      desired_capacity       = 2,
      max_capacity           = 5,
      min_capacity           = 2,
      instance_types         = var.instance_types,
      iam_role_arn           = aws_iam_role.node.arn,
      create_launch_template = var.encrypt_ebs_volume,
      disk_encrypted         = var.encrypt_ebs_volume,
      disk_kms_key_id        = var.encrypt_ebs_volume ? var.kms_key_arn : "",
      force_update_version   = true,
      instance_type          = ["m4.large"] #to be removed in future
    }
  }
```

2023-02-06 18:52 UTC, venky-wandb commented on modules/app_eks/main.tf
> +      instance_types         = ["m4.large"],
I think we'll leave this one as `m5.xlarge` - previously I think this was just falling back to `m4.large` from the root tf module because it was supposed to be `instance_types` but it was `instance_type`. So `m5.xlarge` should definitely be our recommended default.

2023-02-09 16:12 UTC, jsbroks commented on modules/app_eks/main.tf
> +  worker_additional_security_group_ids = var.encrypt_ebs_volume ? [module.eks.cluster_primary_security_group_id] : []
@wandb-zacharyblasczyk can we try rebooting from scratch with ebs enabled and this line removed?

2023-02-13 17:10 UTC, jsbroks commented on modules/app_eks/main.tf
> +  worker_additional_security_group_ids = var.encrypt_ebs_volume ? [module.eks.cluster_primary_security_group_id] : []
Sorry to keep blocking on this. We should really understand why we need this, then I will be happy to approve

2023-02-17 20:07 UTC, closed without merging