Adds aws_s3_bucket_public_access_block for file_storage bucket
wandb/terraform-aws-wandb pull request #5
Opened 2021-11-23 21:03 UTC by zythosec

This will ensure even if https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_account_public_access_block is not specified in a customer account that this bucket cannot have public objects or public policies attached.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block
https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html

2021-11-23 23:02 UTC, jsbroks requested changes

2021-11-23 23:02 UTC, jsbroks commented on modules/file_storage/main.tf
> +resource "aws_s3_bucket_public_access_block" "example" {
probably not call it example

2021-11-23 23:50 UTC, zythosec commented on modules/file_storage/main.tf
> +resource "aws_s3_bucket_public_access_block" "example" {
🤦🏼

2021-11-24 00:07 UTC, zythosec commented on modules/file_storage/main.tf
> +}
Oh nice didn't know this was hooked up.

2021-11-24 15:04 UTC, jsbroks approved these changes

2021-11-30 14:14 UTC, merged

2022-02-10 05:19 UTC, jsbroks commented
This PR is included in version 1.0.0 :tada: